config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
  post 'weather', to: 'home#weather', as: 'weather'
  get 'weather', to: 'home#weather'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'net/http'
class HomeController < ApplicationController
  def weather
    if request.post?
      session[:lat] = params[:lat]
      session[:lon] = params[:lon]

      lat = params[:lat]
      lon = params[:lon]
    else
      lat = session[:lat]
      lon = session[:lon]
    end

    if lat.present? && lon.present?
      apikey = Rails.application.secrets[:openweathermap_api_key]
      url = "https://api.openweathermap.org/data/2.5/weather?lat=#{lat}&lon=#{lon}&units=metric&appid=#{apikey}"
      uri = URI(url)
      res = Net::HTTP.get_response(uri)
      @data = JSON.parse(res.body)
    else
      @error = "Location data is missing."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def modified_icons
    ["01d", "01n", "02d", "02n", "03d", "03n", "04d", "04n", "09d", "09n", "10d", "10n", "11d", "11n", "13d", "13n", "50d", "50n"]
  end
end

app/views/home/index.html.erb
<div class="flex justify-center items-center h-screen">
  <div class="text-center">
    <%= image_tag("logo.png", class: "size-20 mx-auto mb-5") %>
    <p class="mb-2 font-sans capitalize">Please allow location request to your browser</p>
    <button id="getLocation" type="button" class="inline-flex items-center gap-x-1.5 rounded-md bg-black px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black">
      See The Weather
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="m12.75 15 3-3m0 0-3-3m3 3h-7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
      </svg>
    </button>
  </div>
</div>

<%= form_with(url: weather_path, method: :post, id: 'locationForm', style: "display:none;") do |form| %>
  <%= form.hidden_field :lat, id: 'lat' %>
  <%= form.hidden_field :lon, id: 'lon' %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<% end %>

app/views/home/weather.html.erb
<article class="container mx-auto mt-28 px-5">
  <% if @data["weather"] %>
    <div class="grid place-items-center h-full">
      <% if modified_icons.include?(@data["weather"].first["icon"]) %>
        <%= image_tag("animated/#{@data["weather"].first["icon"]}.svg", class: "size-60") %>
      <% else %>
        <img src="https://openweathermap.org/img/wn/<%= @data["weather"].first["icon"] %>@2x.png">
      <% end %>

      <div class="text-3xl"><%= @data[ "weather"].first["main"] %></div>
      <div class="text-sm"><%= @data["weather"].first["description"] %></div>
      <%= "#{@data["main"]["temp"].to_i}°C" %>
    </div>
  <% else %>
    <p>Hava durumu bilgileri alınamadı.</p>
  <% end %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="shortcut icon" type="image/x-icon" href="<%= asset_path('fav.ico') %>">
  </head>

  <body>
    <%# <main class="container mx-auto mt-28 px-5"> #Tailwind comes like this as default %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>